# Alternative configuration using Artifact Registry (recommended for new projects)
# To use this, rename it to cloudbuild.yaml or specify it with: gcloud builds submit --config=cloudbuild-artifact-registry.yaml

steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/aquatic-sustainability:$SHORT_SHA'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/aquatic-sustainability:latest'
      - '.'
    id: 'build-image'

  # Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/aquatic-sustainability:$SHORT_SHA'
    id: 'push-image-sha'
    waitFor: ['build-image']

  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'push'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/aquatic-sustainability:latest'
    id: 'push-image-latest'
    waitFor: ['build-image']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'aquatic-sustainability'
      - '--image'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/aquatic-sustainability:$SHORT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '5000'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--max-instances'
      - '10'
      - '--timeout'
      - '300'
      # Optional: Uncomment if CPU boost is available in your region
      # - '--cpu-boost'
    id: 'deploy-cloud-run'
    waitFor: ['push-image-sha']

# Store images in Artifact Registry
images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/aquatic-sustainability:$SHORT_SHA'
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/aquatic-sustainability:latest'

# Substitution variables (set these when triggering the build)
# _REGION: e.g., us-central1
# _REPOSITORY: e.g., aquatic-sustainability-repo

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '1200s'

